/**
 * Collapsible side pane for the YAML config editor.
 *  - Required atlas.* fields for the selected strategy are starred + chipped.
 *  - "Download searchaas.yaml" serializes the live edit state.
 */
import { useMemo, useState } from "react";
import { dump as yamlDump, load as yamlLoad } from "js-yaml";
import {
  Banner, Button, Chip, CodeBlock, Disclosure, Field, NumberInput,
  Select, Slider, Tabs, TextArea, TextInput,
} from "./UI";
import type { AppConfig, Strategy } from "../lib/types";
import { REQUIRED_ATLAS_FIELDS } from "../lib/types";
import { applySettings } from "../lib/api";

type ConfigTab = "atlas" | "embeddings" | "planner" | "retrieval" | "server";

interface Props {
  collapsed: boolean;
  setCollapsed: (b: boolean) => void;
  config: AppConfig;
  setConfig: (c: AppConfig) => void;
  strategy: Strategy;
  /** FastAPI base URL so the pane can POST /settings directly. */
  fastapiUrl: string;
  /** True while the initial GET /settings hydration is in flight. */
  loading?: boolean;
  /** Error from the GET /settings hydration (null when OK). */
  loadError?: string | null;
  /** Re-fetch GET /settings from the backend (called after a successful Apply). */
  onReload?: () => void;
}

export default function ConfigPane({
  collapsed, setCollapsed, config, setConfig, strategy, fastapiUrl,
  loading = false, loadError = null, onReload,
}: Props) {
  const [tab, setTab] = useState<ConfigTab>("atlas");
  const [applyState, setApplyState] = useState<"idle" | "loading" | "ok" | "error">("idle");
  const [applyError, setApplyError] = useState<string | null>(null);
  // In AutoEmbeddings mode Atlas manages embedding_key / dimensions /
  // relevance_score_fn server-side, so they are null by design and must NOT be
  // flagged as required (otherwise auto mode always shows a false "missing").
  const isAutoEmbed = config.embeddings.provider === "auto";
  const required = (REQUIRED_ATLAS_FIELDS[strategy] ?? []).filter(
    (f) => !(isAutoEmbed && ["embedding_key", "dimensions", "relevance_score_fn"].includes(f)),
  );
  const isRequired = (f: string) => required.includes(f);

  const missing = useMemo(
    () => required.filter((f) => {
      const v = (config.atlas as unknown as Record<string, unknown>)[f];
      return v === undefined || v === null || String(v).trim() === "";
    }),
    [config.atlas, required],
  );

  const yamlText = useMemo(
    () => "# Generated by SearchaaS UI\n" +
          yamlDump(config, { sortKeys: false, lineWidth: 100 }),
    [config],
  );

  const downloadYaml = () => {
    const blob = new Blob([yamlText], { type: "application/x-yaml" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "searchaas.yaml";
    a.click();
    URL.revokeObjectURL(url);
  };

  const update = <K extends keyof AppConfig>(key: K, value: AppConfig[K]) =>
    setConfig({ ...config, [key]: value });
  const updateAtlas = (patch: Partial<AppConfig["atlas"]>) =>
    update("atlas", { ...config.atlas, ...patch });

  /** Switch embeddings provider, resetting the config dict so stale keys
   *  (api keys, dimensions, etc.) don't bleed across provider switches. */
  const setEmbProvider = (provider: string) => {
    const blank: Record<string, Record<string, unknown>> = {
      auto:          { model: "voyage-4" },
      voyageai:      { model: "voyage-4", voyage_api_key: "${VOYAGE_API_KEY}", output_dimension: 512 },
      gemini:        { model: "models/text-embedding-004", google_api_key: "${GOOGLE_API_KEY}" },
      openai:        { model: "text-embedding-3-large", openai_api_key: "${OPENAI_API_KEY}" },
      azure_openai:  { model: "text-embedding-3-large", azure_openai_api_key: "${AZURE_OPENAI_API_KEY}" },
      cohere:        { model: "embed-english-v3.0", cohere_api_key: "${COHERE_API_KEY}" },
      huggingface:   { model_name: "sentence-transformers/all-MiniLM-L6-v2" },
      bedrock_titan: { model_id: "amazon.titan-embed-text-v2:0", region_name: "us-east-1" },
    };
    update("embeddings", {
      provider,
      config: blank[provider] ?? {},
    });
  };

  /** POST the current config to the backend /settings endpoint. */
  const handleApply = async () => {
    setApplyState("loading");
    setApplyError(null);
    try {
      await applySettings(fastapiUrl, {
        atlas: {
          collection:         config.atlas.collection         || undefined,
          vector_index:       config.atlas.vector_index       || undefined,
          search_index:       config.atlas.search_index       || undefined,
          text_key:           config.atlas.text_key           || undefined,
          embedding_key:      config.atlas.embedding_key      || undefined,
          relevance_score_fn: config.atlas.relevance_score_fn || undefined,
          dimensions:         config.atlas.dimensions         || undefined,
        },
        embeddings: {
          provider: config.embeddings.provider || undefined,
          config:   config.embeddings.config   || undefined,
        },
        planner: {
          llm_provider:  config.planner.llm_provider  || undefined,
          config:        config.planner.config        || undefined,
          default_top_k: config.planner.default_top_k || undefined,
        },
        retrieval: {
          default_strategy: config.retrieval.default_strategy || undefined,
          hybrid:  config.retrieval.hybrid  || undefined,
          vector:  config.retrieval.vector  || undefined,
        },
      });
      setApplyState("ok");
      // Re-fetch /settings so the side pane reflects the backend's post-rebuild
      // state (e.g. secrets re-redacted, AutoEmbeddings null-coercion applied).
      onReload?.();
      setTimeout(() => setApplyState("idle"), 3000);
    } catch (e) {
      setApplyState("error");
      setApplyError(String((e as Error).message ?? e));
    }
  };

  /* ── Collapsed rail ── */
  if (collapsed) {
    return (
      <aside className="sidebar">
        <div className="sidebar-rail">
          <button className="btn icon-only" aria-label="Expand configuration"
                  onClick={() => setCollapsed(false)}>›</button>
          <span className="rail-label">Configuration</span>
          <button className="btn icon-only" aria-label="Download YAML"
                  onClick={downloadYaml}>⬇</button>
        </div>
      </aside>
    );
  }

  return (
    <aside className="sidebar">
      <div className="sidebar-head">
        <div className="sidebar-head-title">
          <span className="dot" />
          ⚙️ Configuration
        </div>
        <button className="btn icon-only" aria-label="Collapse configuration"
                onClick={() => setCollapsed(true)}>‹</button>
      </div>

      <div className="sidebar-body">
        {/* Backend hydration status — tells the user where these values came from */}
        {loading && (
          <Banner variant="info">
            Loading config from <code>{fastapiUrl}/settings</code>…
          </Banner>
        )}
        {!loading && loadError && (
          <Banner variant="warn">
            {loadError}
            {onReload && (
              <>
                {" "}
                <a href="#" onClick={(e) => { e.preventDefault(); onReload(); }}>
                  Retry
                </a>
              </>
            )}
          </Banner>
        )}

        {/* Validation banner */}
        {missing.length === 0 ? (
          <Banner variant="success">
            All required <code>atlas.*</code> fields for <b>{strategy}</b> are set.
          </Banner>
        ) : (
          <Banner variant="warn">
            Missing required fields for <b>{strategy}</b>:
            <span style={{ marginLeft: 4 }}>
              {missing.map((m) => <code key={m} style={{ marginRight: 4 }}>{m}</code>)}
            </span>
          </Banner>
        )}

        {/* Required field chips */}
        <div className="chip-row">
          {required.map((f) => (
            <Chip key={f} label={f}
                  variant={missing.includes(f) ? "red" : "green"} />
          ))}
        </div>

        {/* Config tabs */}
        <Tabs<ConfigTab>
          value={tab}
          onChange={setTab}
          options={[
            { value: "atlas",      label: "Atlas" },
            { value: "embeddings", label: "Embeddings" },
            { value: "planner",    label: "Planner" },
            { value: "retrieval",  label: "Retrieval" },
            { value: "server",     label: "Server" },
          ]}
        />

        {/* ── Atlas tab ── */}
        {tab === "atlas" && (
          <>
            <Field label="uri" required={isRequired("uri")}>
              <TextInput value={config.atlas.uri}
                onChange={(e) => updateAtlas({ uri: e.target.value })} />
            </Field>
            <div className="row">
              <Field label="database" required={isRequired("database")}>
                <TextInput value={config.atlas.database}
                  onChange={(e) => updateAtlas({ database: e.target.value })} />
              </Field>
              <Field label="collection" required={isRequired("collection")}>
                <TextInput value={config.atlas.collection}
                  onChange={(e) => updateAtlas({ collection: e.target.value })} />
              </Field>
            </div>

            {["vector", "hybrid", "parent-doc", "auto"].includes(strategy) && (
              <Field label="vector_index" required={isRequired("vector_index")}
                     hint="Atlas Vector Search index name">
                <TextInput value={config.atlas.vector_index}
                  onChange={(e) => updateAtlas({ vector_index: e.target.value })} />
              </Field>
            )}
            {["fulltext", "hybrid", "auto"].includes(strategy) && (
              <Field label="search_index" required={isRequired("search_index")}
                     hint="Atlas Search (Lucene) index name">
                <TextInput value={config.atlas.search_index}
                  onChange={(e) => updateAtlas({ search_index: e.target.value })} />
              </Field>
            )}

            <Field label="text_key" required={isRequired("text_key")}>
              <TextInput value={config.atlas.text_key}
                onChange={(e) => updateAtlas({ text_key: e.target.value })} />
            </Field>

            {["vector", "hybrid", "graph", "parent-doc", "auto"].includes(strategy) && (
              isAutoEmbed ? (
                <Banner variant="info">
                  Auto-embed mode is on — <code>embedding_key</code>,{" "}
                  <code>dimensions</code>, and <code>relevance_score_fn</code> are
                  managed by the Atlas Vector Search index and are not editable here.
                </Banner>
              ) : (
                <>
                  <div className="row">
                    <Field label="embedding_key" required={isRequired("embedding_key")}>
                      <TextInput value={config.atlas.embedding_key}
                        onChange={(e) => updateAtlas({ embedding_key: e.target.value })} />
                    </Field>
                    <Field label="dimensions" required={isRequired("dimensions")}>
                      <NumberInput min={-1} max={8192}
                        value={config.atlas.dimensions}
                        onChange={(e) =>
                          updateAtlas({ dimensions: Number(e.target.value) || -1 })} />
                    </Field>
                  </div>
                  <Field label="relevance_score_fn">
                    <Select
                      value={config.atlas.relevance_score_fn}
                      onChange={(e) =>
                        updateAtlas({ relevance_score_fn: e.target.value as AppConfig["atlas"]["relevance_score_fn"] })}
                      options={["cosine", "euclidean", "dotProduct"]}
                    />
                  </Field>
                </>
              )
            )}
          </>
        )}

        {/* ── Embeddings tab ── */}
        {tab === "embeddings" && (
          <>
            <Field
              label="provider"
              hint={isAutoEmbed
                ? "MongoDB Atlas auto-embeds documents and queries server-side."
                : undefined}
            >
              <Select
                value={config.embeddings.provider}
                onChange={(e) => setEmbProvider(e.target.value)}
                options={["auto","voyageai","gemini","openai","azure_openai","cohere","huggingface","bedrock_titan"]}
              />
            </Field>

            {isAutoEmbed ? (
              <>
                <Banner variant="info">
                  <strong>Auto-embed mode.</strong> No API keys or dimensions
                  needed — Atlas Vector Search handles embedding inside the
                  index. The <code>model</code> below must match the
                  <code> autoEmbed</code> field declared in your vector index.
                </Banner>
                <Field
                  label="model"
                  required
                  hint="Examples: voyage-4, voyage-3-large, text-embedding-3-large, amazon.titan-embed-text-v2:0"
                >
                  <TextInput
                    value={String(config.embeddings.config.model ?? "")}
                    onChange={(e) =>
                      update("embeddings", {
                        ...config.embeddings,
                        config: { ...config.embeddings.config, model: e.target.value },
                      })
                    }
                    placeholder="voyage-4"
                  />
                </Field>
              </>
            ) : (
              <Field label="config (YAML)">
                <TextArea
                  rows={6}
                  className="textarea mono"
                  value={yamlDump(config.embeddings.config, { sortKeys: false }).trim()}
                  onChange={(e) => {
                    try {
                      const parsed = yamlLoad(e.target.value);
                      update("embeddings", {
                        ...config.embeddings,
                        config: (parsed ?? {}) as Record<string, unknown>,
                      });
                    } catch { /* ignore mid-typing errors */ }
                  }}
                />
              </Field>
            )}
          </>
        )}

        {/* ── Planner tab ── */}
        {tab === "planner" && (
          <>
            <Field label="llm_provider">
              <Select
                value={config.planner.llm_provider}
                onChange={(e) =>
                  update("planner", { ...config.planner, llm_provider: e.target.value })}
                options={["gemini","openai","azure_openai","anthropic","bedrock"]}
              />
            </Field>
            <Field label="default_top_k">
              <NumberInput min={1} max={100}
                value={config.planner.default_top_k}
                onChange={(e) =>
                  update("planner", {
                    ...config.planner,
                    default_top_k: Number(e.target.value) || 20,
                  })} />
            </Field>
            <Field label="config (YAML)">
              <TextArea
                rows={6}
                className="textarea mono"
                value={yamlDump(config.planner.config, { sortKeys: false }).trim()}
                onChange={(e) => {
                  try {
                    const parsed = yamlLoad(e.target.value);
                    update("planner", {
                      ...config.planner,
                      config: (parsed ?? {}) as Record<string, unknown>,
                    });
                  } catch { /* ignore */ }
                }}
              />
            </Field>
          </>
        )}

        {/* ── Retrieval tab ── */}
        {tab === "retrieval" && (
          <>
            <Field label="default_strategy">
              <Select
                value={config.retrieval.default_strategy}
                onChange={(e) =>
                  update("retrieval", {
                    ...config.retrieval,
                    default_strategy: e.target.value as AppConfig["retrieval"]["default_strategy"],
                  })}
                options={["vector","fulltext","hybrid","graph","parent-doc"]}
              />
            </Field>
            <Field label={`hybrid.vector_weight  (${config.retrieval.hybrid.vector_weight.toFixed(2)})`}>
              <Slider
                min={0} max={1} step={0.05}
                value={config.retrieval.hybrid.vector_weight}
                onChange={(n) =>
                  update("retrieval", {
                    ...config.retrieval,
                    hybrid: { ...config.retrieval.hybrid, vector_weight: n },
                  })}
              />
            </Field>
            <Field label={`hybrid.fulltext_weight  (${config.retrieval.hybrid.fulltext_weight.toFixed(2)})`}>
              <Slider
                min={0} max={1} step={0.05}
                value={config.retrieval.hybrid.fulltext_weight}
                onChange={(n) =>
                  update("retrieval", {
                    ...config.retrieval,
                    hybrid: { ...config.retrieval.hybrid, fulltext_weight: n },
                  })}
              />
            </Field>
            <Field label="vector.num_candidates">
              <NumberInput min={10} max={5000}
                value={config.retrieval.vector.num_candidates}
                onChange={(e) =>
                  update("retrieval", {
                    ...config.retrieval,
                    vector: { num_candidates: Number(e.target.value) || 200 },
                  })} />
            </Field>
          </>
        )}

        {/* ── Server tab ── */}
        {tab === "server" && (
          <>
            <div className="row">
              <Field label="host">
                <TextInput value={config.server.host}
                  onChange={(e) =>
                    update("server", { ...config.server, host: e.target.value })} />
              </Field>
              <Field label="port">
                <NumberInput value={config.server.port}
                  onChange={(e) =>
                    update("server", { ...config.server, port: Number(e.target.value) })} />
              </Field>
            </div>
            <div className="row">
              <Field label="mcp_host">
                <TextInput value={config.server.mcp_host}
                  onChange={(e) =>
                    update("server", { ...config.server, mcp_host: e.target.value })} />
              </Field>
              <Field label="mcp_port">
                <NumberInput value={config.server.mcp_port}
                  onChange={(e) =>
                    update("server", { ...config.server, mcp_port: Number(e.target.value) })} />
              </Field>
            </div>
            <Field label="mcp_transport">
              <Select
                value={config.server.mcp_transport}
                onChange={(e) =>
                  update("server", { ...config.server, mcp_transport: e.target.value as AppConfig["server"]["mcp_transport"] })}
                options={["streamable-http","stdio","sse"]}
              />
            </Field>
            <Field label="log_level">
              <Select
                value={config.server.log_level}
                onChange={(e) =>
                  update("server", { ...config.server, log_level: e.target.value as AppConfig["server"]["log_level"] })}
                options={["debug","info","warning","error"]}
              />
            </Field>
          </>
        )}

        {/* Actions */}
        <div className="flex mt-12" style={{ gap: 8 }}>
          <Button
            variant="primary"
            loading={applyState === "loading"}
            onClick={handleApply}
            style={{ flex: 1 }}
          >
            {applyState === "ok" ? "✓ Applied" : "▶ Apply to Backend"}
          </Button>
          <Button onClick={downloadYaml}>⬇ YAML</Button>
          {/* "Reset" now re-pulls the live config from the backend
              (searchaas.yaml + .env) so the user can never resurrect stale
              hardcoded defaults that would silently override the server. */}
          <Button
            onClick={() => onReload?.()}
            disabled={!onReload || loading}
            title="Re-fetch the live config from the backend (searchaas.yaml + .env)"
          >
            {loading ? "↻ Loading…" : "↻ Reload from backend"}
          </Button>
        </div>
        {applyState === "ok" && (
          <div style={{ marginTop: 6 }}>
            <Banner variant="success">Settings applied — backend container rebuilt.</Banner>
          </div>
        )}
        {applyState === "error" && applyError && (
          <div style={{ marginTop: 6 }}>
            <Banner variant="danger">{applyError}</Banner>
          </div>
        )}

        <Disclosure summary="Preview YAML">
          <CodeBlock code={yamlText} />
        </Disclosure>
      </div>
    </aside>
  );
}
